# SPDX-FileCopyrightText: 2026 CC834
# SPDX-License-Identifier: GPL-3.0-only
# Give only Plasma Keyboard a separate remembered volume/mute setting.
stream.rules = [
  {
    matches = [
      { node.name = "plasma-keyboard" media.class = "Stream/Output/Audio" }
      { application.id = "org.kde.plasma.keyboard" media.class = "Stream/Output/Audio" }
    ]
    actions = {
      update-props = {
        media.role = "Keyboard"
        state.restore-target = false
      }
    }
  }
]
